# Generated by Django 5.0.2 on 2024-02-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_autofetchmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofetchmodel',
            name='name',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
