# Generated by Django 5.0.2 on 2024-02-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_autofetchmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=500, null=True)),
                ('record_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
